on:
  workflow_dispatch:
  push:
    branches:
      - main

name: quarto-render-publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    env:
      R_VERSION: '4.5.1'

    permissions: 
      contents: write
      pages: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

        # I created this list of dependencies with {dockerfiler}, so it's 
        # probably overly ambitious in installing stuff that might already be 
        # in the runner image, but it works and it's better than playing 
        # whack-a-mole with GHA to find any missing dependencies, so whatever ğŸ¤·â€â™‚ï¸
        #
        # dock <- dockerfiler::dock_from_renv(
        #   "renv.lock",
        #   FROM = "rocker/r-ver", AS = "renv-base",
        #   repos = c(
        #     CRAN = "https://cran.rstudio.com/",
        #     tinytable = "https://vincentarelbundock.r-universe.dev"
        #   ),
        #   use_pak = FALSE
        # )
      - name: Install system dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            make \
            pandoc

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ env.R_VERSION }}

      - name: Install R dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      - name: Render and publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
